service: probando

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "S3:*"
      Resource: "arn:aws:s3:::hider${opt:stage, 'dev'}/*"
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  uploader:
    handler: handler.handle
    events:
      - httpApi: 
          method : POST 
          path : /file/upload
          cors : true
    environment:
      BUCKET: hider${opt:stage, 'dev'}
resources:
  Resources:
    HiderBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hider${opt:stage, 'dev'}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"