service: probando

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  uploader:
    handler: handler.handle
    events:
      - httpApi: 
          method : POST 
          path : /file/upload
    environment:
      BUCKET: modusland${opt:stage, 'dev'}
resources:
  Resources:
    ModuslandBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: modusland
        AccessControl: PublicRead