service: probando

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  uploader:
    handler: handler.handle
    events:
      - httpApi: 
          method : POST 
          path : /file/upload
    environment:
      BUCKET: hider${opt:stage, 'dev'}
resources:
  Resources:
    HiderBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hider${opt:stage, 'dev'}
        AccessControl: PublicRead
    UploadRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: upload-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:PutObjectAcl
                  Resource:
                    !Sub
                      - "arn:aws:s3:::${BucketName}/*"
                      - {BucketName: !Ref HiderBucket}